name: Bump Versions
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
'on':
  schedule:
  - cron: 30 17 * * WED
  workflow_dispatch: null
jobs:
  bump-versions:
    name: Bump Package Versions
    if: github.repository_owner == 'wdrx70xn'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/viamrobotics/rdk-devenv:amd64
    timeout-minutes: 10
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Update go dependencies
      id: gobump
      run: "sudo chown -R testbot .\nsudo -u testbot bash -lc 'go get go.viam.com/rdk'\n\
        sudo -u testbot bash -lc 'go get go.viam.com/api'\nsudo -u testbot bash -lc\
        \ 'go mod tidy'\nGEN_DIFF=$(git status -s)\n\nif [ -n \"$GEN_DIFF\" ]; then\n\
        \    echo \"needs_pr=1\" >> $GITHUB_OUTPUT\nfi\n"
    - name: Add + Commit + Open PR
      if: steps.gobump.outputs.needs_pr == 1
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: '[WORKFLOW] Updating go dependencies'
        branch: workflow/update-dependencies
        delete-branch: true
        base: main
        title: Automated Go Dependencies Update
        body: This is an auto-generated PR to update go dependencies. Please confirm
          tests are passing before merging.
